/**
 * Auto-incrementing counter for generating unique names.
 *
 * Used by devtools to identify signals, tags, etc. when no explicit name is provided.
 * Format: `#{kind}-{counter}` (e.g., "#mutable-1", "#computed-42", "#tag-5")
 *
 * The `#` prefix indicates an auto-generated name (vs user-provided).
 * Use `isAutoGeneratedName()` to check if a name was auto-generated.
 *
 * @module nameGenerator
 */

let counter = 0;

/**
 * Separate counter for unique signal IDs.
 * This counter is independent from name counter and should never be reset.
 */
let uidCounter = 0;

/**
 * Generate a unique signal ID.
 * Format: "sig-{n}" (e.g., "sig-1", "sig-2", "sig-42")
 *
 * This ID is:
 * - Auto-generated and immutable
 * - Unique across all signals in the application lifecycle
 * - Independent from displayName (which can be changed)
 *
 * @returns Unique signal ID
 */
export function nextUid(): string {
  return `s:${++uidCounter}`;
}

/**
 * Prefix for auto-generated names.
 * Used to distinguish from user-provided names.
 */
export const AUTO_NAME_PREFIX = "#";

/**
 * Valid prefixes for auto-generated names.
 */
export type NamePrefix = "mutable" | "computed" | "tag";

/**
 * Generate a unique name with the given prefix.
 * @param prefix - The prefix to use: "mutable", "computed", or "tag"
 * @returns Name in format "#{prefix}-{n}"
 */
export function nextName(prefix: NamePrefix): string {
  return `${AUTO_NAME_PREFIX}${prefix}-${++counter}`;
}

/**
 * Check if a name was auto-generated (starts with #).
 * @param name - The name to check
 * @returns true if the name was auto-generated
 */
export function isAutoGeneratedName(name: string): boolean {
  return name.startsWith(AUTO_NAME_PREFIX);
}

/**
 * Prefix a name with AUTO_NAME_PREFIX (#).
 * Useful for generating internal signal names in operators.
 * @param name - The name to prefix
 * @returns Name prefixed with #
 *
 * @example
 * autoPrefix("takeLast_internal") // "#takeLast_internal"
 * autoPrefix(`delay(${source.displayName})`) // "#delay(count)"
 */
export function autoPrefix(name: string): string {
  return `${AUTO_NAME_PREFIX}${name}-${++counter}`;
}

/**
 * Reset counter (for testing purposes only).
 * @internal
 */
export function resetCounter(): void {
  counter = 0;
}

/**
 * Get current counter value (for debugging/devtools).
 * @internal
 */
export function getCounter(): number {
  return counter;
}
