import { describe, it, expect } from "vitest";
import {
  parseSearchQuery,
  matchesSignalSearch,
  matchesTagSearch,
  matchesEventSearch,
} from "./searchUtils";
import { signal } from "../../signal";

describe("searchUtils", () => {
  const isAutoGenerated = (name: string) => name.startsWith("#");

  describe("parseSearchQuery", () => {
    it("should parse simple text query", () => {
      const query = parseSearchQuery("user");
      expect(query.defaultQuery).toBe("user");
      expect(query.fields.size).toBe(0);
      expect(query.includeAutoGenerated).toBe(false);
    });

    it("should parse field-specific query", () => {
      const query = parseSearchQuery("name:user");
      expect(query.fields.get("name")).toBe("user");
      expect(query.defaultQuery).toBeUndefined();
    });

    it("should parse multiple field queries", () => {
      const query = parseSearchQuery("name:user kind:mutable");
      expect(query.fields.get("name")).toBe("user");
      expect(query.fields.get("kind")).toBe("mutable");
    });

    it("should parse regex pattern", () => {
      const query = parseSearchQuery("/user.*count/i");
      expect(query.isRegex).toBe(true);
      expect(query.defaultQuery).toBeInstanceOf(RegExp);
      expect((query.defaultQuery as RegExp).test("userCount")).toBe(true);
    });

    it("should handle auto-generated override", () => {
      const query = parseSearchQuery("#signal");
      expect(query.includeAutoGenerated).toBe(true);
      expect(query.defaultQuery).toBe("signal");
    });

    it("should parse boolean fields", () => {
      const query = parseSearchQuery("error:true disposed:false");
      expect(query.fields.get("error")).toBe("true");
      expect(query.fields.get("disposed")).toBe("false");
    });

    it("should handle mixed field and default query", () => {
      const query = parseSearchQuery("name:user test");
      expect(query.fields.get("name")).toBe("user");
      expect(query.defaultQuery).toBe("test");
    });
  });

  describe("matchesSignalSearch", () => {
    const mockSignal = {
      name: "userCount",
      id: "sig1",
      kind: "mutable" as const,
      signal: signal(42),
      source: { file: "App.tsx", line: 10 },
      tags: new Set(["form", "user"]),
      errorCount: 0,
      disposed: false,
    };

    it("should match by name", () => {
      const query = parseSearchQuery("name:user");
      expect(
        matchesSignalSearch(mockSignal, query, isAutoGenerated, false)
      ).toBe(true);
    });

    it("should match by value", () => {
      const query = parseSearchQuery("value:42");
      expect(
        matchesSignalSearch(mockSignal, query, isAutoGenerated, false)
      ).toBe(true);
    });

    it("should match by file", () => {
      const query = parseSearchQuery("file:App.tsx");
      expect(
        matchesSignalSearch(mockSignal, query, isAutoGenerated, false)
      ).toBe(true);
    });

    it("should match by tag", () => {
      const query = parseSearchQuery("tag:form");
      expect(
        matchesSignalSearch(mockSignal, query, isAutoGenerated, false)
      ).toBe(true);
    });

    it("should match by kind", () => {
      const query = parseSearchQuery("kind:mutable");
      expect(
        matchesSignalSearch(mockSignal, query, isAutoGenerated, false)
      ).toBe(true);
    });

    it("should match default query across name, value, and file", () => {
      const query = parseSearchQuery("user");
      expect(
        matchesSignalSearch(mockSignal, query, isAutoGenerated, false)
      ).toBe(true);
    });

    it("should filter by error status", () => {
      const signalWithError = { ...mockSignal, errorCount: 1 };
      const query = parseSearchQuery("error:true");
      expect(
        matchesSignalSearch(signalWithError, query, isAutoGenerated, false)
      ).toBe(true);
      expect(
        matchesSignalSearch(mockSignal, query, isAutoGenerated, false)
      ).toBe(false);
    });

    it("should filter by disposed status", () => {
      const disposedSignal = { ...mockSignal, disposed: true };
      const query = parseSearchQuery("disposed:true");
      expect(
        matchesSignalSearch(disposedSignal, query, isAutoGenerated, false)
      ).toBe(true);
      expect(
        matchesSignalSearch(mockSignal, query, isAutoGenerated, false)
      ).toBe(false);
    });

    it("should respect auto-generated filter", () => {
      const autoSignal = { ...mockSignal, name: "#sig123" };
      const query = parseSearchQuery("sig");
      expect(
        matchesSignalSearch(autoSignal, query, isAutoGenerated, false)
      ).toBe(false);
      
      const queryWithHash = parseSearchQuery("#sig");
      expect(
        matchesSignalSearch(autoSignal, queryWithHash, isAutoGenerated, false)
      ).toBe(true);
    });

    it("should respect showAutoGenerated toggle", () => {
      const autoSignal = { ...mockSignal, name: "#sig123" };
      const query = parseSearchQuery("sig");
      // With showAutoGenerated=false, auto-generated signals are filtered out
      expect(
        matchesSignalSearch(autoSignal, query, isAutoGenerated, false)
      ).toBe(false);
      // With showAutoGenerated=true, auto-generated signals are shown
      expect(
        matchesSignalSearch(autoSignal, query, isAutoGenerated, true)
      ).toBe(true);
    });

    it("should handle signals that throw when accessing value", () => {
      const errorSignal = {
        ...mockSignal,
        signal: {
          get: () => {
            throw new Error("Signal in error state");
          },
        },
      };
      
      // Value search should not crash, should return false
      const query = parseSearchQuery("value:42");
      expect(
        matchesSignalSearch(errorSignal, query, isAutoGenerated, false)
      ).toBe(false);
      
      // Default search should still work (matches name/file, not value)
      const defaultQuery = parseSearchQuery("userCount");
      expect(
        matchesSignalSearch(errorSignal, defaultQuery, isAutoGenerated, false)
      ).toBe(true);
    });
  });

  describe("matchesTagSearch", () => {
    const mockTag = {
      id: "formTag",
    };

    it("should match by name", () => {
      const query = parseSearchQuery("name:form");
      expect(matchesTagSearch(mockTag, query, isAutoGenerated, false)).toBe(true);
    });

    it("should match default query", () => {
      const query = parseSearchQuery("form");
      expect(matchesTagSearch(mockTag, query, isAutoGenerated, false)).toBe(true);
    });
  });

  describe("matchesEventSearch", () => {
    const getSignalName = (id: string) => {
      if (id === "sig1") return "userCount";
      return undefined;
    };

    it("should match by signal name", () => {
      const event = {
        type: "signal:change",
        signalId: "sig1",
        value: 42,
      };
      const query = parseSearchQuery("name:user");
      expect(
        matchesEventSearch(event, query, getSignalName)
      ).toBe(true);
    });

    it("should match by event type", () => {
      const event = {
        type: "signal:change",
        signalId: "sig1",
      };
      const query = parseSearchQuery("change");
      expect(
        matchesEventSearch(event, query, getSignalName)
      ).toBe(true);
    });

    it("should match by value", () => {
      const event = {
        type: "signal:change",
        signalId: "sig1",
        value: 42,
      };
      const query = parseSearchQuery("value:42");
      expect(
        matchesEventSearch(event, query, getSignalName)
      ).toBe(true);
    });
  });
});

