/**
 * Signal Kind Filters Component
 * Filters for signal types (all, mutable, computed, error, disposed)
 */

import { memo } from "react";
import type { SignalInfo } from "../../../devtools/types";
import * as styles from "../../styles";
import type { SignalKindFilter } from "../../types";

interface SignalKindFiltersProps {
  filter: SignalKindFilter;
  setFilter: (filter: SignalKindFilter) => void;
  stats: {
    mutableCount: number;
    computedCount: number;
    signalsWithErrors: number;
    disposedCount: number;
  };
  filteredSignals: SignalInfo[];
  signals: Map<string, SignalInfo>;
  showAutoGenerated: boolean;
}

export const SignalKindFilters = memo(function SignalKindFilters({
  filter,
  setFilter,
  stats,
  filteredSignals,
  signals,
  showAutoGenerated,
}: SignalKindFiltersProps) {
  return (
    <>
      {(["all", "mutable", "computed", "error", "disposed"] as const).map((kind) => {
        const isActive = filter === kind;
        const label =
          kind === "all"
            ? "A"
            : kind === "mutable"
            ? "M"
            : kind === "computed"
            ? "C"
            : kind === "error"
            ? "E"
            : "D";
        const color =
          kind === "mutable"
            ? styles.colors.mutable
            : kind === "computed"
            ? styles.colors.computed
            : kind === "error"
            ? styles.colors.error
            : kind === "disposed"
            ? "#666"
            : styles.colors.text;
        const countDisplay =
          kind === "all"
            ? !showAutoGenerated && filteredSignals.length !== signals.size
              ? `${filteredSignals.length} / ${signals.size}`
              : `${signals.size}`
            : kind === "mutable"
            ? `${stats.mutableCount}`
            : kind === "computed"
            ? `${stats.computedCount}`
            : kind === "error"
            ? `${stats.signalsWithErrors}`
            : `${stats.disposedCount}`;

        const hasErrors = kind === "error" && stats.signalsWithErrors > 0;

        return (
          <button
            key={kind}
            style={{
              padding: "3px 8px",
              fontSize: "10px",
              fontWeight: 600,
              backgroundColor:
                isActive || hasErrors ? color + "33" : styles.colors.bgHover,
              border: `1px solid ${isActive || hasErrors ? color : styles.colors.border}`,
              borderRadius: "4px",
              color: isActive || hasErrors ? color : styles.colors.textMuted,
              cursor: "pointer",
              fontFamily: "inherit",
              display: "flex",
              alignItems: "center",
              gap: "4px",
              ...(hasErrors && !isActive && { animation: "pulse 2s infinite" }),
            }}
            onClick={() => setFilter(kind)}
            title={`Show ${kind} signals`}
          >
            {label}
            <span style={{ fontWeight: 400, fontSize: "9px", opacity: 0.8 }}>
              {countDisplay}
            </span>
          </button>
        );
      })}
    </>
  );
});

