/**
 * Signal Option Filters Component
 * Options for bookmark filtering, sort order, and auto-generated signals
 */

import { memo } from "react";
import * as styles from "../../styles";
import { FilterGroup } from "../shared";
import { IconStar } from "../../icons";

interface SignalOptionFiltersProps {
  showBookmarksOnly: boolean;
  setShowBookmarksOnly: (show: boolean) => void;
  bookmarkedSignals: Set<string>;
  recentActivitySort: boolean;
  setRecentActivitySort: (sort: boolean) => void;
  flashAutoToggle: boolean;
  showAutoGenerated: boolean;
  updateShowAutoGenerated: (show: boolean) => void;
  clearFlashAutoToggle: () => void;
  autoGeneratedCount: number;
}

export const SignalOptionFilters = memo(function SignalOptionFilters({
  showBookmarksOnly,
  setShowBookmarksOnly,
  bookmarkedSignals,
  recentActivitySort,
  setRecentActivitySort,
  flashAutoToggle,
  showAutoGenerated,
  updateShowAutoGenerated,
  clearFlashAutoToggle,
  autoGeneratedCount,
}: SignalOptionFiltersProps) {
  return (
    <FilterGroup>
      <button
        style={{
          padding: "3px 8px",
          fontSize: "10px",
          backgroundColor: showBookmarksOnly
            ? styles.colors.warning + "33"
            : styles.colors.bgHover,
          border: `1px solid ${showBookmarksOnly ? styles.colors.warning : styles.colors.border}`,
          borderRadius: "4px",
          color: showBookmarksOnly ? styles.colors.warning : styles.colors.textMuted,
          cursor: "pointer",
          fontFamily: "inherit",
          display: "flex",
          alignItems: "center",
          gap: "4px",
        }}
        onClick={(e) => {
          e.stopPropagation();
          setShowBookmarksOnly(!showBookmarksOnly);
        }}
        title={showBookmarksOnly ? "Show all signals" : "Show bookmarked signals only"}
      >
        <IconStar size={10} filled={showBookmarksOnly} />
        {bookmarkedSignals.size > 0 && (
          <span style={{ fontSize: "9px" }}>{bookmarkedSignals.size}</span>
        )}
      </button>
      <button
        style={{
          padding: "3px 8px",
          fontSize: "10px",
          backgroundColor: recentActivitySort
            ? styles.colors.warning + "33"
            : styles.colors.bgHover,
          border: `1px solid ${recentActivitySort ? styles.colors.warning : styles.colors.border}`,
          borderRadius: "4px",
          color: recentActivitySort ? styles.colors.warning : styles.colors.textMuted,
          cursor: "pointer",
          fontFamily: "inherit",
          display: "flex",
          alignItems: "center",
          lineHeight: 1,
        }}
        onClick={() => setRecentActivitySort(!recentActivitySort)}
        title={recentActivitySort ? "Sort by default (active first)" : "Sort by recent activity"}
      >
        🕐
      </button>
      <button
        style={{
          padding: "3px 8px",
          fontSize: "10px",
          backgroundColor: flashAutoToggle
            ? styles.colors.warning + "44"
            : showAutoGenerated
            ? styles.colors.accent + "33"
            : styles.colors.bgHover,
          border: `1px solid ${
            flashAutoToggle
              ? styles.colors.warning
              : showAutoGenerated
              ? styles.colors.accent
              : styles.colors.border
          }`,
          borderRadius: "4px",
          color: flashAutoToggle
            ? styles.colors.warning
            : showAutoGenerated
            ? styles.colors.accent
            : styles.colors.textMuted,
          cursor: "pointer",
          fontFamily: "inherit",
          transition: "all 0.3s ease",
          animation: flashAutoToggle ? "pulse-warning 0.5s ease-in-out infinite" : "none",
          boxShadow: flashAutoToggle ? `0 0 8px ${styles.colors.warning}66` : "none",
        }}
        onClick={() => {
          updateShowAutoGenerated(!showAutoGenerated);
          if (flashAutoToggle) {
            clearFlashAutoToggle();
          }
        }}
        title={
          flashAutoToggle
            ? "New auto-generated signals created! Click to show."
            : showAutoGenerated
            ? "Click to hide auto-generated signals"
            : "Click to show auto-generated signals"
        }
      >
        #auto <span style={{ fontWeight: 400, opacity: 0.8 }}>{autoGeneratedCount}</span>
      </button>
    </FilterGroup>
  );
});

