/**
 * Tests for usePanelConfig Hook
 */

import { describe, it, expect, beforeEach, afterEach, vi } from "vitest";
import { renderHook, act } from "@testing-library/react";
import { usePanelConfig } from "./usePanelConfig";
import { STORAGE_KEY, DEFAULT_CONFIG } from "../config";

describe("usePanelConfig", () => {
  beforeEach(() => {
    localStorage.clear();
    // Reset body styles
    document.body.style.paddingBottom = "";
    document.body.style.paddingLeft = "";
  });

  afterEach(() => {
    localStorage.clear();
    document.body.style.paddingBottom = "";
    document.body.style.paddingLeft = "";
  });

  describe("initial state", () => {
    it("should load default config when no saved config exists", () => {
      const { result } = renderHook(() => usePanelConfig());
      const [state] = result.current;

      expect(state.isExpanded).toBe(DEFAULT_CONFIG.expanded);
      expect(state.position).toBe(DEFAULT_CONFIG.position);
      expect(state.activeTab).toBe(DEFAULT_CONFIG.activeTab);
      expect(state.showAutoGenerated).toBe(DEFAULT_CONFIG.showAutoGenerated);
    });

    it("should load saved config from localStorage", () => {
      localStorage.setItem(
        STORAGE_KEY,
        JSON.stringify({
          expanded: true,
          position: "bottom",
          activeTab: "events",
        })
      );

      const { result } = renderHook(() => usePanelConfig());
      const [state] = result.current;

      expect(state.isExpanded).toBe(true);
      expect(state.position).toBe("bottom");
      expect(state.activeTab).toBe("events");
    });
  });

  describe("togglePanel", () => {
    it("should toggle expanded state", () => {
      const { result } = renderHook(() => usePanelConfig());

      expect(result.current[0].isExpanded).toBe(false);

      act(() => {
        result.current[1].togglePanel();
      });

      expect(result.current[0].isExpanded).toBe(true);

      act(() => {
        result.current[1].togglePanel();
      });

      expect(result.current[0].isExpanded).toBe(false);
    });

    it("should persist expanded state to localStorage", () => {
      const { result } = renderHook(() => usePanelConfig());

      act(() => {
        result.current[1].togglePanel();
      });

      const saved = JSON.parse(localStorage.getItem(STORAGE_KEY) || "{}");
      expect(saved.expanded).toBe(true);
    });
  });

  describe("togglePosition", () => {
    it("should toggle between bottom and left positions", () => {
      const { result } = renderHook(() => usePanelConfig());

      // Default is "left"
      expect(result.current[0].position).toBe("left");

      act(() => {
        result.current[1].togglePosition();
      });

      expect(result.current[0].position).toBe("bottom");

      act(() => {
        result.current[1].togglePosition();
      });

      expect(result.current[0].position).toBe("left");
    });

    it("should persist position to localStorage", () => {
      const { result } = renderHook(() => usePanelConfig());

      act(() => {
        result.current[1].togglePosition();
      });

      const saved = JSON.parse(localStorage.getItem(STORAGE_KEY) || "{}");
      expect(saved.position).toBe("bottom");
    });
  });

  describe("updateActiveTab", () => {
    it("should update active tab", () => {
      const { result } = renderHook(() => usePanelConfig());

      act(() => {
        result.current[1].updateActiveTab("events");
      });

      expect(result.current[0].activeTab).toBe("events");
    });

    it("should persist active tab to localStorage", () => {
      const { result } = renderHook(() => usePanelConfig());

      act(() => {
        result.current[1].updateActiveTab("tags");
      });

      const saved = JSON.parse(localStorage.getItem(STORAGE_KEY) || "{}");
      expect(saved.activeTab).toBe("tags");
    });
  });

  describe("updateShowAutoGenerated", () => {
    it("should update showAutoGenerated flag", () => {
      const { result } = renderHook(() => usePanelConfig());

      expect(result.current[0].showAutoGenerated).toBe(false);

      act(() => {
        result.current[1].updateShowAutoGenerated(true);
      });

      expect(result.current[0].showAutoGenerated).toBe(true);
    });
  });

  describe("resetConfig", () => {
    it("should reset all config to defaults", () => {
      const { result } = renderHook(() => usePanelConfig());

      // Make some changes
      act(() => {
        result.current[1].togglePanel();
        result.current[1].togglePosition();
        result.current[1].updateActiveTab("events");
        result.current[1].updateShowAutoGenerated(true);
      });

      // Reset
      act(() => {
        result.current[1].resetConfig();
      });

      const [state] = result.current;
      expect(state.isExpanded).toBe(DEFAULT_CONFIG.expanded);
      expect(state.position).toBe(DEFAULT_CONFIG.position);
      expect(state.activeTab).toBe(DEFAULT_CONFIG.activeTab);
      expect(state.showAutoGenerated).toBe(DEFAULT_CONFIG.showAutoGenerated);
    });

    it("should clear localStorage", () => {
      const { result } = renderHook(() => usePanelConfig());

      act(() => {
        result.current[1].togglePanel();
      });

      expect(localStorage.getItem(STORAGE_KEY)).not.toBeNull();

      act(() => {
        result.current[1].resetConfig();
      });

      expect(localStorage.getItem(STORAGE_KEY)).toBeNull();
    });
  });

  describe("snapshot config", () => {
    it("should update snapshot settings", () => {
      const { result } = renderHook(() => usePanelConfig());

      act(() => {
        result.current[1].updateSnapshotOnInit(true);
      });
      expect(result.current[0].snapshotOnInit).toBe(true);

      act(() => {
        result.current[1].updateSnapshotAutoInterval(true);
      });
      expect(result.current[0].snapshotAutoInterval).toBe(true);

      act(() => {
        result.current[1].updateSnapshotBookmarkedOnly(true);
      });
      expect(result.current[0].snapshotBookmarkedOnly).toBe(true);
    });
  });

  describe("handleSettingsChange", () => {
    it("should update multiple settings at once", () => {
      const { result } = renderHook(() => usePanelConfig());

      act(() => {
        result.current[1].handleSettingsChange({
          autoRemoveDisposedTimer: 5,
          autoSnapshotInterval: 10,
          signalHistoryLimit: 20,
        });
      });

      const [state] = result.current;
      expect(state.autoRemoveDisposedTimer).toBe(5);
      expect(state.autoSnapshotIntervalSeconds).toBe(10);
      expect(state.signalHistoryLimit).toBe(20);
    });

    it("should persist settings to localStorage", () => {
      const { result } = renderHook(() => usePanelConfig());

      act(() => {
        result.current[1].handleSettingsChange({
          autoRemoveDisposedTimer: 5,
          autoSnapshotInterval: 10,
          signalHistoryLimit: 20,
        });
      });

      const saved = JSON.parse(localStorage.getItem(STORAGE_KEY) || "{}");
      expect(saved.autoRemoveDisposedTimer).toBe(5);
      expect(saved.autoSnapshotIntervalSeconds).toBe(10);
      expect(saved.signalHistoryLimit).toBe(20);
    });
  });

  describe("config modal", () => {
    it("should toggle config modal open/close", () => {
      const { result } = renderHook(() => usePanelConfig());

      expect(result.current[0].isConfigModalOpen).toBe(false);

      act(() => {
        result.current[1].setIsConfigModalOpen(true);
      });

      expect(result.current[0].isConfigModalOpen).toBe(true);

      act(() => {
        result.current[1].setIsConfigModalOpen(false);
      });

      expect(result.current[0].isConfigModalOpen).toBe(false);
    });
  });
});

