/**
 * Panel Configuration Hook
 * Manages panel position, size, expansion state, and resize handling
 */

import { useState, useCallback, useEffect, useRef } from "react";
import type { PanelPosition } from "../styles";
import * as styles from "../styles";
import {
  loadConfig,
  saveConfig,
  clearConfig,
  DEFAULT_CONFIG,
} from "../config";
import { updateDevToolsConfig } from "../../devtools";
import type { Tab } from "../types";

export interface PanelConfigState {
  isExpanded: boolean;
  position: PanelPosition;
  activeTab: Tab;
  showAutoGenerated: boolean;
  sizeBottom: number | null;
  sizeLeft: number | null;
  isResizing: boolean;
  isMobile: boolean;
  snapshotOnInit: boolean;
  snapshotAutoInterval: boolean;
  snapshotBookmarkedOnly: boolean;
  autoRemoveDisposedTimer: number;
  autoSnapshotIntervalSeconds: number;
  signalHistoryLimit: number;
  isConfigModalOpen: boolean;
}

export interface PanelConfigActions {
  togglePanel: () => void;
  togglePosition: () => void;
  updateActiveTab: (tab: Tab) => void;
  updateShowAutoGenerated: (show: boolean) => void;
  resetConfig: () => void;
  handleResizeStart: (e: React.MouseEvent | React.TouchEvent) => void;
  updateSnapshotOnInit: (value: boolean) => void;
  updateSnapshotAutoInterval: (value: boolean) => void;
  updateSnapshotBookmarkedOnly: (value: boolean) => void;
  setIsConfigModalOpen: (open: boolean) => void;
  handleSettingsChange: (settings: {
    autoRemoveDisposedTimer: number;
    autoSnapshotInterval: number;
    signalHistoryLimit: number;
  }) => void;
}

export function usePanelConfig(): [PanelConfigState, PanelConfigActions] {
  // Load initial config
  const initialConfig = useRef(loadConfig()).current;

  // Panel state
  const [isExpanded, setIsExpanded] = useState(initialConfig.expanded);
  const [position, setPosition] = useState<PanelPosition>(
    initialConfig.position
  );
  const [activeTab, setActiveTab] = useState<Tab>(initialConfig.activeTab);
  const [showAutoGenerated, setShowAutoGenerated] = useState(
    initialConfig.showAutoGenerated
  );
  const [sizeBottom, setSizeBottom] = useState<number | null>(
    initialConfig.sizeBottom
  );
  const [sizeLeft, setSizeLeft] = useState<number | null>(
    initialConfig.sizeLeft
  );
  const [isResizing, setIsResizing] = useState(false);
  const [isMobile, setIsMobile] = useState(
    () => typeof window !== "undefined" && window.innerWidth <= 768
  );

  // Snapshot config state
  const [snapshotOnInit, setSnapshotOnInit] = useState(
    initialConfig.snapshotOnInit
  );
  const [snapshotAutoInterval, setSnapshotAutoInterval] = useState(
    initialConfig.snapshotAutoInterval
  );
  const [snapshotBookmarkedOnly, setSnapshotBookmarkedOnly] = useState(
    initialConfig.snapshotBookmarkedOnly
  );

  // Config modal state
  const [isConfigModalOpen, setIsConfigModalOpen] = useState(false);
  const [autoRemoveDisposedTimer, setAutoRemoveDisposedTimer] = useState(
    initialConfig.autoRemoveDisposedTimer
  );
  const [autoSnapshotIntervalSeconds, setAutoSnapshotIntervalSeconds] =
    useState(initialConfig.autoSnapshotIntervalSeconds);
  const [signalHistoryLimit, setSignalHistoryLimit] = useState(
    initialConfig.signalHistoryLimit
  );

  // Mobile mode detection
  useEffect(() => {
    const checkMobile = () => {
      const mobile = window.innerWidth <= 768;
      setIsMobile(mobile);
      if (mobile) {
        setPosition((prev) => (prev !== "bottom" ? "bottom" : prev));
      }
    };

    checkMobile();
    window.addEventListener("resize", checkMobile);
    return () => window.removeEventListener("resize", checkMobile);
  }, []);

  // Toggle panel expanded state
  const togglePanel = useCallback(() => {
    setIsExpanded((prev) => {
      const next = !prev;
      saveConfig({ expanded: next });
      return next;
    });
  }, []);

  // Toggle position
  const togglePosition = useCallback(() => {
    setPosition((prev) => {
      const next = prev === "bottom" ? "left" : "bottom";
      saveConfig({ position: next });
      return next;
    });
  }, []);

  // Update active tab
  const updateActiveTab = useCallback((tab: Tab) => {
    setActiveTab(tab);
    saveConfig({ activeTab: tab });
  }, []);

  // Update show auto-generated
  const updateShowAutoGenerated = useCallback((show: boolean) => {
    setShowAutoGenerated(show);
    saveConfig({ showAutoGenerated: show });
  }, []);

  // Reset config
  const resetConfig = useCallback(() => {
    clearConfig();
    setIsExpanded(DEFAULT_CONFIG.expanded);
    setPosition(DEFAULT_CONFIG.position);
    setActiveTab(DEFAULT_CONFIG.activeTab);
    setShowAutoGenerated(DEFAULT_CONFIG.showAutoGenerated);
    setSizeBottom(DEFAULT_CONFIG.sizeBottom);
    setSizeLeft(DEFAULT_CONFIG.sizeLeft);
    setAutoRemoveDisposedTimer(DEFAULT_CONFIG.autoRemoveDisposedTimer);
    setAutoSnapshotIntervalSeconds(DEFAULT_CONFIG.autoSnapshotIntervalSeconds);
    setSignalHistoryLimit(DEFAULT_CONFIG.signalHistoryLimit);
    updateDevToolsConfig({ maxHistory: DEFAULT_CONFIG.signalHistoryLimit });
  }, []);

  // Handle settings change
  const handleSettingsChange = useCallback(
    (settings: {
      autoRemoveDisposedTimer: number;
      autoSnapshotInterval: number;
      signalHistoryLimit: number;
    }) => {
      setAutoRemoveDisposedTimer(settings.autoRemoveDisposedTimer);
      setAutoSnapshotIntervalSeconds(settings.autoSnapshotInterval);
      setSignalHistoryLimit(settings.signalHistoryLimit);
      saveConfig({
        autoRemoveDisposedTimer: settings.autoRemoveDisposedTimer,
        autoSnapshotIntervalSeconds: settings.autoSnapshotInterval,
        signalHistoryLimit: settings.signalHistoryLimit,
      });
      updateDevToolsConfig({ maxHistory: settings.signalHistoryLimit });
    },
    []
  );

  // Snapshot config updates
  const updateSnapshotOnInit = useCallback((value: boolean) => {
    setSnapshotOnInit(value);
    saveConfig({ snapshotOnInit: value });
  }, []);

  const updateSnapshotAutoInterval = useCallback((value: boolean) => {
    setSnapshotAutoInterval(value);
    saveConfig({ snapshotAutoInterval: value });
  }, []);

  const updateSnapshotBookmarkedOnly = useCallback((value: boolean) => {
    setSnapshotBookmarkedOnly(value);
    saveConfig({ snapshotBookmarkedOnly: value });
  }, []);

  // Resize handlers
  const handleResizeStart = useCallback(
    (e: React.MouseEvent | React.TouchEvent) => {
      e.preventDefault();
      e.stopPropagation();
      setIsResizing(true);

      const isTouch = "touches" in e;
      const startY = isTouch ? e.touches[0].clientY : e.clientY;
      const startX = isTouch ? e.touches[0].clientX : e.clientX;
      const startSize =
        position === "bottom"
          ? sizeBottom ?? styles.PANEL_SIZE_EXPANDED_BOTTOM
          : sizeLeft ?? styles.PANEL_SIZE_EXPANDED_LEFT;

      const handleMove = (moveEvent: MouseEvent | TouchEvent) => {
        const isTouchMove = "touches" in moveEvent;
        const currentY = isTouchMove
          ? moveEvent.touches[0].clientY
          : moveEvent.clientY;
        const currentX = isTouchMove
          ? moveEvent.touches[0].clientX
          : moveEvent.clientX;

        if (position === "bottom") {
          const delta = startY - currentY;
          const newSize = Math.max(
            styles.PANEL_MIN_SIZE_BOTTOM,
            Math.min(styles.PANEL_MAX_SIZE_BOTTOM, startSize + delta)
          );
          setSizeBottom(newSize);
        } else {
          const delta = currentX - startX;
          const newSize = Math.max(
            styles.PANEL_MIN_SIZE_LEFT,
            Math.min(styles.PANEL_MAX_SIZE_LEFT, startSize + delta)
          );
          setSizeLeft(newSize);
        }
      };

      const handleEnd = () => {
        setIsResizing(false);
        document.removeEventListener("mousemove", handleMove);
        document.removeEventListener("mouseup", handleEnd);
        document.removeEventListener("touchmove", handleMove);
        document.removeEventListener("touchend", handleEnd);
        document.removeEventListener("touchcancel", handleEnd);
        document.body.style.cursor = "";
        document.body.style.userSelect = "";

        if (position === "bottom") {
          saveConfig({ sizeBottom: sizeBottom });
        } else {
          saveConfig({ sizeLeft: sizeLeft });
        }
      };

      document.addEventListener("mousemove", handleMove);
      document.addEventListener("mouseup", handleEnd);
      document.addEventListener("touchmove", handleMove, { passive: false });
      document.addEventListener("touchend", handleEnd);
      document.addEventListener("touchcancel", handleEnd);
      document.body.style.cursor =
        position === "bottom" ? "ns-resize" : "ew-resize";
      document.body.style.userSelect = "none";
    },
    [position, sizeBottom, sizeLeft]
  );

  // Save size after resize ends
  useEffect(() => {
    if (!isResizing) {
      if (position === "bottom" && sizeBottom !== null) {
        saveConfig({ sizeBottom });
      } else if (position === "left" && sizeLeft !== null) {
        saveConfig({ sizeLeft });
      }
    }
  }, [isResizing, position, sizeBottom, sizeLeft]);

  // Manage body padding
  useEffect(() => {
    const updateBodyPadding = () => {
      if (position === "bottom" && isExpanded) {
        const height = sizeBottom ?? styles.PANEL_SIZE_EXPANDED_BOTTOM;
        document.body.style.paddingBottom = `${height}px`;
        document.body.style.paddingLeft = "";
      } else if (position === "left" && isExpanded) {
        const width = sizeLeft ?? styles.PANEL_SIZE_EXPANDED_LEFT;
        document.body.style.paddingLeft = `${width}px`;
        document.body.style.paddingBottom = "";
      } else {
        if (position === "bottom") {
          document.body.style.paddingBottom = `${styles.PANEL_SIZE_COLLAPSED}px`;
          document.body.style.paddingLeft = "";
        } else {
          document.body.style.paddingLeft = `${styles.PANEL_SIZE_COLLAPSED}px`;
          document.body.style.paddingBottom = "";
        }
      }
    };

    updateBodyPadding();

    return () => {
      document.body.style.paddingBottom = "";
      document.body.style.paddingLeft = "";
    };
  }, [position, isExpanded, sizeBottom, sizeLeft]);

  const state: PanelConfigState = {
    isExpanded,
    position,
    activeTab,
    showAutoGenerated,
    sizeBottom,
    sizeLeft,
    isResizing,
    isMobile,
    snapshotOnInit,
    snapshotAutoInterval,
    snapshotBookmarkedOnly,
    autoRemoveDisposedTimer,
    autoSnapshotIntervalSeconds,
    signalHistoryLimit,
    isConfigModalOpen,
  };

  const actions: PanelConfigActions = {
    togglePanel,
    togglePosition,
    updateActiveTab,
    updateShowAutoGenerated,
    resetConfig,
    handleResizeStart,
    updateSnapshotOnInit,
    updateSnapshotAutoInterval,
    updateSnapshotBookmarkedOnly,
    setIsConfigModalOpen,
    handleSettingsChange,
  };

  return [state, actions];
}

