/**
 * DevTools Panel Configuration
 * Storage and config management utilities
 */

import type { DevToolsConfig } from "./types";

export const STORAGE_KEY = "rextive-devtools-config";
export const BOOKMARKS_STORAGE_KEY = "rextive-devtools-bookmarks";

export const DEFAULT_CONFIG: DevToolsConfig = {
  position: "left",
  expanded: false,
  activeTab: "signals",
  showAutoGenerated: false,
  sizeBottom: null,
  sizeLeft: null,
  snapshotOnInit: false,
  snapshotAutoInterval: false,
  snapshotBookmarkedOnly: false,
  autoRemoveDisposedTimer: 3,
  autoSnapshotIntervalSeconds: 5,
  signalHistoryLimit: 5,
};

/**
 * Load config from localStorage
 */
export const loadConfig = (): DevToolsConfig => {
  try {
    const saved = localStorage.getItem(STORAGE_KEY);
    if (saved) {
      const parsed = JSON.parse(saved);
      return { ...DEFAULT_CONFIG, ...parsed };
    }
  } catch {
    // Ignore localStorage errors
  }
  return DEFAULT_CONFIG;
};

/**
 * Save config to localStorage
 */
export const saveConfig = (config: Partial<DevToolsConfig>) => {
  try {
    const current = loadConfig();
    localStorage.setItem(
      STORAGE_KEY,
      JSON.stringify({ ...current, ...config })
    );
  } catch {
    // Ignore localStorage errors
  }
};

/**
 * Clear all persisted config
 */
export const clearConfig = () => {
  try {
    localStorage.removeItem(STORAGE_KEY);
  } catch {
    // Ignore localStorage errors
  }
};

/**
 * Load bookmarks from localStorage
 */
export const loadBookmarks = (): Set<string> => {
  try {
    const saved = localStorage.getItem(BOOKMARKS_STORAGE_KEY);
    if (saved) {
      return new Set(JSON.parse(saved));
    }
  } catch {
    // Ignore localStorage errors
  }
  return new Set<string>();
};

/**
 * Save bookmarks to localStorage
 */
export const saveBookmarks = (bookmarks: Set<string>) => {
  try {
    localStorage.setItem(
      BOOKMARKS_STORAGE_KEY,
      JSON.stringify(Array.from(bookmarks))
    );
  } catch {
    // Ignore localStorage errors
  }
};

