/**
 * Tests for DevTools Panel Configuration
 */

import { describe, it, expect, beforeEach, afterEach } from "vitest";
import {
  STORAGE_KEY,
  BOOKMARKS_STORAGE_KEY,
  DEFAULT_CONFIG,
  loadConfig,
  saveConfig,
  clearConfig,
  loadBookmarks,
  saveBookmarks,
} from "./config";

describe("config", () => {
  beforeEach(() => {
    localStorage.clear();
  });

  afterEach(() => {
    localStorage.clear();
  });

  describe("loadConfig", () => {
    it("should return default config when no saved config exists", () => {
      const config = loadConfig();
      expect(config).toEqual(DEFAULT_CONFIG);
    });

    it("should load saved config from localStorage", () => {
      const savedConfig = { expanded: true, position: "bottom" as const };
      localStorage.setItem(STORAGE_KEY, JSON.stringify(savedConfig));

      const config = loadConfig();
      expect(config.expanded).toBe(true);
      expect(config.position).toBe("bottom");
    });

    it("should merge saved config with defaults", () => {
      const partialConfig = { expanded: true };
      localStorage.setItem(STORAGE_KEY, JSON.stringify(partialConfig));

      const config = loadConfig();
      expect(config.expanded).toBe(true);
      expect(config.position).toBe(DEFAULT_CONFIG.position);
      expect(config.activeTab).toBe(DEFAULT_CONFIG.activeTab);
    });

    it("should handle invalid JSON gracefully", () => {
      localStorage.setItem(STORAGE_KEY, "invalid json");

      const config = loadConfig();
      expect(config).toEqual(DEFAULT_CONFIG);
    });
  });

  describe("saveConfig", () => {
    it("should save config to localStorage", () => {
      saveConfig({ expanded: true });

      const saved = JSON.parse(localStorage.getItem(STORAGE_KEY) || "{}");
      expect(saved.expanded).toBe(true);
    });

    it("should merge with existing config", () => {
      saveConfig({ expanded: true });
      saveConfig({ position: "bottom" as const });

      const saved = JSON.parse(localStorage.getItem(STORAGE_KEY) || "{}");
      expect(saved.expanded).toBe(true);
      expect(saved.position).toBe("bottom");
    });

    it("should preserve other config values", () => {
      localStorage.setItem(
        STORAGE_KEY,
        JSON.stringify({ expanded: true, activeTab: "tags" })
      );
      saveConfig({ position: "bottom" as const });

      const saved = JSON.parse(localStorage.getItem(STORAGE_KEY) || "{}");
      expect(saved.expanded).toBe(true);
      expect(saved.activeTab).toBe("tags");
      expect(saved.position).toBe("bottom");
    });
  });

  describe("clearConfig", () => {
    it("should remove config from localStorage", () => {
      localStorage.setItem(STORAGE_KEY, JSON.stringify({ expanded: true }));

      clearConfig();

      expect(localStorage.getItem(STORAGE_KEY)).toBeNull();
    });

    it("should not throw when config does not exist", () => {
      expect(() => clearConfig()).not.toThrow();
    });
  });

  describe("loadBookmarks", () => {
    it("should return empty set when no bookmarks exist", () => {
      const bookmarks = loadBookmarks();
      expect(bookmarks.size).toBe(0);
    });

    it("should load bookmarks from localStorage", () => {
      localStorage.setItem(
        BOOKMARKS_STORAGE_KEY,
        JSON.stringify(["sig1", "sig2"])
      );

      const bookmarks = loadBookmarks();
      expect(bookmarks.has("sig1")).toBe(true);
      expect(bookmarks.has("sig2")).toBe(true);
      expect(bookmarks.size).toBe(2);
    });

    it("should handle invalid JSON gracefully", () => {
      localStorage.setItem(BOOKMARKS_STORAGE_KEY, "invalid json");

      const bookmarks = loadBookmarks();
      expect(bookmarks.size).toBe(0);
    });
  });

  describe("saveBookmarks", () => {
    it("should save bookmarks to localStorage", () => {
      const bookmarks = new Set(["sig1", "sig2"]);
      saveBookmarks(bookmarks);

      const saved = JSON.parse(
        localStorage.getItem(BOOKMARKS_STORAGE_KEY) || "[]"
      );
      expect(saved).toContain("sig1");
      expect(saved).toContain("sig2");
    });

    it("should handle empty set", () => {
      const bookmarks = new Set<string>();
      saveBookmarks(bookmarks);

      const saved = JSON.parse(
        localStorage.getItem(BOOKMARKS_STORAGE_KEY) || "[]"
      );
      expect(saved).toEqual([]);
    });
  });

  describe("DEFAULT_CONFIG", () => {
    it("should have sensible defaults", () => {
      expect(DEFAULT_CONFIG.position).toBe("left");
      expect(DEFAULT_CONFIG.expanded).toBe(false);
      expect(DEFAULT_CONFIG.activeTab).toBe("signals");
      expect(DEFAULT_CONFIG.showAutoGenerated).toBe(false);
      expect(DEFAULT_CONFIG.autoRemoveDisposedTimer).toBe(3);
      expect(DEFAULT_CONFIG.signalHistoryLimit).toBe(5);
    });
  });
});

