/**
 * DevTools Panel Component
 *
 * A bottom drawer panel for inspecting Rextive signals and tags.
 * Uses pure React state (no signals) to avoid circular dependencies.
 * Responsive design for mobile devices.
 */

import React, { useRef, useMemo, memo } from "react";
import { clearDisposed, deleteChain } from "../devtools";
import { isAutoGeneratedName } from "../utils/nameGenerator";

// Types
import type { Tab } from "./types";
import { formatTime, getTabLabel } from "./utils";

// Hooks
import { useFlash } from "./hooks/useFlash";
import { useSnapshots } from "./hooks/useSnapshots";
import { usePanelConfig } from "./hooks/usePanelConfig";
import { useDevToolsData } from "./hooks/useDevToolsData";
import { useUIState } from "./hooks/useUIState";

// Styles
import * as styles from "./styles";

// Tab components
import { SignalsTab } from "./tabs/SignalsTab";
import { TagsTab } from "./tabs/TagsTab";
import { EventsTab } from "./tabs/EventsTab";
import { ChainsTab } from "./tabs/ChainsTab";
import { SnapshotsTab } from "./tabs/SnapshotsTab";

// Icons
import { IconTrash } from "./icons";

// Components
import { PanelHeader } from "./components/PanelHeader";
import { ConfigModal } from "./components/ConfigModal";
import { SearchHelpModal } from "./SearchHelpModal";
import { ValueDiffModal } from "./ValueDiffModal";
import { SnapshotDiffModal, CURRENT_STATE_ID } from "./SnapshotDiffModal";
import { TabBar, TabContent, FilterSeparator } from "./components/shared";
import {
  SignalKindFilters,
  SignalOptionFilters,
  EventKindFilters,
  SnapshotFilters,
} from "./components/filters";

export const DevToolsPanel = memo(
  function DevToolsPanel(): React.ReactElement | null {
    // Refs
    const panelRef = useRef<HTMLDivElement>(null);
    const showAutoGeneratedRef = useRef(false);

    // Flash hook
    const {
      flashingSignals,
      flashingTabs,
      flashAutoToggle,
      flashSignal,
      flashTab,
      setFlashAutoToggle,
      clearFlashAutoToggle,
      cleanup: cleanupFlash,
    } = useFlash();

    // Panel config hook
    const [config, configActions] = usePanelConfig();
    showAutoGeneratedRef.current = config.showAutoGenerated;

    // UI state hook
    const [ui, uiActions] = useUIState();

    // DevTools data hook
    const [data, dataActions] = useDevToolsData({
      showAutoGeneratedRef,
      autoRemoveDisposedTimer: config.autoRemoveDisposedTimer,
      activeTab: config.activeTab,
      flashSignal,
      flashTab,
      setFlashAutoToggle,
      cleanupFlash,
    });

    // Snapshots hook
    const {
      snapshots,
      expandedSnapshot,
      setExpandedSnapshot,
      editingSnapshotId,
      setEditingSnapshotId,
      editingSnapshotName,
      setEditingSnapshotName,
      snapshotSearch,
      setSnapshotSearch,
      takeSnapshot,
      takeSnapshotForTag,
      deleteSnapshot,
      renameSnapshot,
      revertSnapshot,
      revertSingleSignal,
      clearAllSnapshots,
      getCurrentStateSignals,
    } = useSnapshots({
      signals: data.signals,
      bookmarkedSignals: ui.bookmarkedSignals,
      snapshotBookmarkedOnly: config.snapshotBookmarkedOnly,
      snapshotOnInit: config.snapshotOnInit,
      snapshotAutoInterval: config.snapshotAutoInterval,
      autoSnapshotIntervalSeconds: config.autoSnapshotIntervalSeconds,
      enabled: data.enabled,
      flashTab,
    });

    // Snapshot diff state
    const [snapshotDiffOpen, setSnapshotDiffOpen] = React.useState(false);
    const [snapshotDiff1Id, setSnapshotDiff1Id] = React.useState<string | null>(
      null
    );
    const [snapshotDiff2Id, setSnapshotDiff2Id] = React.useState<string | null>(
      null
    );

    const compareSnapshotWithCurrent = React.useCallback(
      (snapshotId: string) => {
        setSnapshotDiff1Id(snapshotId);
        setSnapshotDiff2Id(CURRENT_STATE_ID);
        setSnapshotDiffOpen(true);
      },
      []
    );

    // Filter signals and events
    const filteredSignals = uiActions.filterSignals(
      data.signals,
      config.showAutoGenerated
    );
    const filteredEvents = uiActions.filterEvents(data.events, data.signals);

    // Filter tags
    const filteredTags = useMemo(() => {
      return Array.from(data.tags.values()).filter((t) => {
        // Simple filter - just check if name matches search
        if (!ui.searchQuery) return true;
        return t.id.toLowerCase().includes(ui.searchQuery.toLowerCase());
      });
    }, [data.tags, ui.searchQuery]);

    // Pre-compute dependents map
    const dependentsMap = useMemo(() => {
      const map = new Map<string, Array<{ id: string; name: string }>>();
      for (const [, info] of data.signals) {
        if (info.depIds) {
          for (const depId of info.depIds) {
            const existing = map.get(depId) || [];
            existing.push({ id: info.id, name: info.name });
            map.set(depId, existing);
          }
        }
      }
      return map;
    }, [data.signals]);

    // Count auto-generated signals
    const autoGeneratedCount = useMemo(() => {
      let count = 0;
      for (const s of data.signals.values()) {
        if (isAutoGeneratedName(s.name)) count++;
      }
      return count;
    }, [data.signals]);

    // Memoized tabs array
    const tabs = useMemo(
      () =>
        (["signals", "snaps", "tags", "events", "chains"] as Tab[]).map(
          (tab) => ({
            id: tab,
            label: getTabLabel(tab),
          })
        ),
      []
    );

    const handleTabChange = React.useCallback(
      (tabId: string) => configActions.updateActiveTab(tabId as Tab),
      [configActions]
    );

    // Memoized searchBox props
    const searchBoxProps = useMemo(
      () =>
        uiActions.getSearchBoxProps(
          config.activeTab,
          snapshotSearch,
          setSnapshotSearch
        ),
      [uiActions, config.activeTab, snapshotSearch, setSnapshotSearch]
    );

    // Render content based on active tab
    const renderContent = () => {
      if (!data.enabled) {
        return (
          <div style={styles.warningBoxStyles}>
            <div style={{ marginBottom: "4px" }}>⚠️ DevTools not enabled</div>
            <div style={{ fontSize: "10px", opacity: 0.8 }}>
              Call{" "}
              <code
                style={{
                  backgroundColor: "rgba(0,0,0,0.3)",
                  padding: "1px 4px",
                  borderRadius: "2px",
                }}
              >
                enableDevTools()
              </code>{" "}
              before creating signals
            </div>
          </div>
        );
      }

      switch (config.activeTab) {
        case "signals":
          return (
            <SignalsTab
              signals={data.signals}
              filteredSignals={filteredSignals}
              position={config.position}
              expandedSignal={ui.expandedSignal}
              setExpandedSignal={uiActions.setExpandedSignal}
              hoveredItem={ui.hoveredItem}
              setHoveredItem={uiActions.setHoveredItem}
              flashingSignals={flashingSignals}
              bookmarkedSignals={ui.bookmarkedSignals}
              toggleBookmark={uiActions.toggleBookmark}
              editingSignal={ui.editingSignal}
              setEditingSignal={uiActions.setEditingSignal}
              editValue={ui.editValue}
              setEditValue={uiActions.setEditValue}
              editError={ui.editError}
              setEditError={uiActions.setEditError}
              searchQuery={ui.searchQuery}
              setSearchQuery={uiActions.setSearchQuery}
              recentActivitySort={ui.recentActivitySort}
              setSignalKindFilter={uiActions.setSignalKindFilter}
              updateActiveTab={configActions.updateActiveTab}
              setCompareModal={uiActions.setCompareModal}
              dependentsMap={dependentsMap}
              deleteSignal={dataActions.deleteSignal}
            />
          );
        case "tags":
          return (
            <TagsTab
              tags={data.tags}
              filteredTags={filteredTags}
              signals={data.signals}
              position={config.position}
              searchQuery={ui.searchQuery}
              expandedTag={ui.expandedTag}
              setExpandedTag={uiActions.setExpandedTag}
              hoveredItem={ui.hoveredItem}
              setHoveredItem={uiActions.setHoveredItem}
              setSearchQuery={uiActions.setSearchQuery}
              setSignalKindFilter={uiActions.setSignalKindFilter}
              updateActiveTab={configActions.updateActiveTab}
              takeSnapshotForTag={takeSnapshotForTag}
            />
          );
        case "events":
          return (
            <EventsTab
              events={data.events}
              filteredEvents={filteredEvents}
              signals={data.signals}
              expandedEvents={ui.expandedEvents}
              setExpandedEvents={uiActions.setExpandedEvents}
              setSearchQuery={uiActions.setSearchQuery}
              setSignalKindFilter={uiActions.setSignalKindFilter}
              updateActiveTab={configActions.updateActiveTab}
            />
          );
        case "chains":
          return (
            <ChainsTab
              chains={data.chains}
              signals={data.signals}
              chainFilter={ui.chainFilter}
              expandedChain={ui.expandedChain}
              setExpandedChain={uiActions.setExpandedChain}
              setSearchQuery={uiActions.setSearchQuery}
              setSignalKindFilter={uiActions.setSignalKindFilter}
              updateActiveTab={configActions.updateActiveTab}
              deleteChain={deleteChain}
              refreshChains={dataActions.refreshChains}
            />
          );
        case "snaps":
          return (
            <SnapshotsTab
              snapshots={snapshots}
              signals={data.signals}
              position={config.position}
              snapshotSearch={snapshotSearch}
              expandedSnapshot={expandedSnapshot}
              setExpandedSnapshot={setExpandedSnapshot}
              editingSnapshotId={editingSnapshotId}
              setEditingSnapshotId={setEditingSnapshotId}
              editingSnapshotName={editingSnapshotName}
              setEditingSnapshotName={setEditingSnapshotName}
              deleteSnapshot={deleteSnapshot}
              renameSnapshot={renameSnapshot}
              revertSnapshot={revertSnapshot}
              revertSingleSignal={revertSingleSignal}
              compareSnapshotWithCurrent={compareSnapshotWithCurrent}
              setSearchQuery={uiActions.setSearchQuery}
              setSignalKindFilter={uiActions.setSignalKindFilter}
              updateActiveTab={configActions.updateActiveTab}
              setCompareModal={uiActions.setCompareModal}
            />
          );
      }
    };

    const currentSize =
      config.position === "bottom" ? config.sizeBottom : config.sizeLeft;

    return (
      <>
        <style>
          {`
          @keyframes pulse-warning {
            0%, 100% { opacity: 1; transform: scale(1); }
            50% { opacity: 0.8; transform: scale(1.05); }
          }
        `}
        </style>
        <div style={styles.panelContainerStyles(config.position)}>
          <div
            ref={panelRef}
            style={{
              ...styles.panelStyles(
                config.isExpanded,
                config.position,
                currentSize ?? undefined,
                config.isResizing
              ),
              position: "relative",
            }}
          >
            {/* Resize handle */}
            {config.isExpanded && (
              <div
                style={styles.resizeHandleStyles(
                  config.position,
                  config.isResizing
                )}
                onMouseDown={configActions.handleResizeStart}
                onTouchStart={configActions.handleResizeStart}
              >
                <div style={styles.resizeHandleGripStyles(config.position)} />
              </div>
            )}

            {/* Header */}
            <PanelHeader
              position={config.position}
              isExpanded={config.isExpanded}
              isMobile={config.isMobile}
              onTogglePanel={configActions.togglePanel}
              onTogglePosition={configActions.togglePosition}
              onOpenSettings={() => configActions.setIsConfigModalOpen(true)}
              onResetConfig={configActions.resetConfig}
            />

            {/* Tabs + Content */}
            {config.isExpanded && (
              <>
                <TabBar
                  tabs={tabs}
                  activeTab={config.activeTab}
                  onTabChange={handleTabChange}
                  flashingTabs={flashingTabs}
                />

                <TabContent
                  searchBox={searchBoxProps}
                  filterBar={
                    config.activeTab === "signals" ? (
                      <>
                        <SignalKindFilters
                          filter={ui.signalKindFilter}
                          setFilter={uiActions.setSignalKindFilter}
                          stats={data.stats}
                          filteredSignals={filteredSignals}
                          signals={data.signals}
                          showAutoGenerated={config.showAutoGenerated}
                        />
                        <SignalOptionFilters
                          showBookmarksOnly={ui.showBookmarksOnly}
                          setShowBookmarksOnly={uiActions.setShowBookmarksOnly}
                          bookmarkedSignals={ui.bookmarkedSignals}
                          recentActivitySort={ui.recentActivitySort}
                          setRecentActivitySort={
                            uiActions.setRecentActivitySort
                          }
                          flashAutoToggle={flashAutoToggle}
                          showAutoGenerated={config.showAutoGenerated}
                          updateShowAutoGenerated={
                            configActions.updateShowAutoGenerated
                          }
                          clearFlashAutoToggle={clearFlashAutoToggle}
                          autoGeneratedCount={autoGeneratedCount}
                        />
                      </>
                    ) : config.activeTab === "events" ? (
                      <>
                        <EventKindFilters
                          filter={ui.eventKindFilter}
                          setFilter={uiActions.setEventKindFilter}
                          events={data.events}
                        />
                        <FilterSeparator />
                        <button
                          style={{
                            padding: "3px 8px",
                            fontSize: "10px",
                            backgroundColor: styles.colors.bgHover,
                            border: `1px solid ${styles.colors.border}`,
                            borderRadius: "4px",
                            color: styles.colors.textMuted,
                            cursor:
                              data.events.length === 0
                                ? "not-allowed"
                                : "pointer",
                            opacity: data.events.length === 0 ? 0.5 : 1,
                            fontFamily: "inherit",
                          }}
                          onClick={dataActions.clearEvents}
                          disabled={data.events.length === 0}
                          title="Clear all events"
                        >
                          Clear
                        </button>
                      </>
                    ) : config.activeTab === "snaps" ? (
                      <SnapshotFilters
                        takeSnapshot={takeSnapshot}
                        snapshotBookmarkedOnly={config.snapshotBookmarkedOnly}
                        updateSnapshotBookmarkedOnly={
                          configActions.updateSnapshotBookmarkedOnly
                        }
                        bookmarkedSignals={ui.bookmarkedSignals}
                        snapshots={snapshots}
                        setSnapshotDiffOpen={setSnapshotDiffOpen}
                        snapshotOnInit={config.snapshotOnInit}
                        updateSnapshotOnInit={
                          configActions.updateSnapshotOnInit
                        }
                        snapshotAutoInterval={config.snapshotAutoInterval}
                        updateSnapshotAutoInterval={
                          configActions.updateSnapshotAutoInterval
                        }
                        autoSnapshotIntervalSeconds={
                          config.autoSnapshotIntervalSeconds
                        }
                      />
                    ) : undefined
                  }
                  actionBar={
                    config.activeTab === "snaps" && snapshots.length > 0 ? (
                      <button
                        style={{
                          padding: "4px 10px",
                          fontSize: "10px",
                          backgroundColor: styles.colors.bgHover,
                          border: `1px solid ${styles.colors.border}`,
                          borderRadius: "4px",
                          color: styles.colors.textMuted,
                          cursor: "pointer",
                          fontFamily: "inherit",
                          display: "flex",
                          alignItems: "center",
                          gap: "4px",
                        }}
                        onClick={clearAllSnapshots}
                        title="Clear all snapshots"
                      >
                        <IconTrash size={12} /> Clear All
                      </button>
                    ) : config.activeTab === "signals" &&
                      ui.signalKindFilter === "disposed" &&
                      data.stats.disposedCount > 0 ? (
                      <button
                        style={{
                          padding: "4px 10px",
                          fontSize: "10px",
                          backgroundColor: "#66666633",
                          border: `1px solid #666`,
                          borderRadius: "4px",
                          color: "#888",
                          cursor: "pointer",
                          fontFamily: "inherit",
                          display: "flex",
                          alignItems: "center",
                          gap: "4px",
                          whiteSpace: "nowrap",
                        }}
                        onClick={(e) => {
                          e.stopPropagation();
                          clearDisposed();
                        }}
                        title={`Clear all ${
                          data.stats.disposedCount
                        } disposed signal${
                          data.stats.disposedCount !== 1 ? "s" : ""
                        }`}
                      >
                        <IconTrash size={12} /> Clear All Disposed (
                        {data.stats.disposedCount})
                      </button>
                    ) : undefined
                  }
                >
                  {renderContent()}
                </TabContent>
              </>
            )}
          </div>
          <SearchHelpModal
            isOpen={ui.showSearchHelp}
            onClose={() => uiActions.setShowSearchHelp(false)}
          />
          {ui.compareModal && (
            <ValueDiffModal
              isOpen={!!ui.compareModal}
              onClose={() => uiActions.setCompareModal(null)}
              signalName={
                data.signals.get(ui.compareModal.signalId)?.name ||
                ui.compareModal.signalId
              }
              currentValue={ui.compareModal.currentValue}
              historyValue={ui.compareModal.historyValue}
              historyTimestamp={ui.compareModal.historyTimestamp}
              formatTime={formatTime}
            />
          )}
          <SnapshotDiffModal
            isOpen={snapshotDiffOpen}
            onClose={() => {
              setSnapshotDiffOpen(false);
              setSnapshotDiff1Id(null);
              setSnapshotDiff2Id(null);
            }}
            snapshots={snapshots}
            snapshot1Id={snapshotDiff1Id}
            snapshot2Id={snapshotDiff2Id}
            onSelectSnapshot1={setSnapshotDiff1Id}
            onSelectSnapshot2={setSnapshotDiff2Id}
            currentStateSignals={getCurrentStateSignals()}
          />
          <ConfigModal
            isOpen={config.isConfigModalOpen}
            onClose={() => configActions.setIsConfigModalOpen(false)}
            settings={{
              autoRemoveDisposedTimer: config.autoRemoveDisposedTimer,
              autoSnapshotInterval: config.autoSnapshotIntervalSeconds,
              signalHistoryLimit: config.signalHistoryLimit,
            }}
            onSettingsChange={configActions.handleSettingsChange}
          />
        </div>
      </>
    );
  }
);
