/**
 * Types for DevTools Panel
 */

import type { DevToolsEvent } from "../devtools/types";
import type { PanelPosition } from "./styles";

export type Tab = "signals" | "snaps" | "tags" | "events" | "chains";

export type SignalKindFilter = "all" | "mutable" | "computed" | "error" | "disposed";

export type EventKindFilter = "all" | "error" | "update" | "create" | "dispose";

export interface DevToolsConfig {
  position: PanelPosition;
  expanded: boolean;
  activeTab: Tab;
  showAutoGenerated: boolean;
  sizeBottom: number | null;
  sizeLeft: number | null;
  snapshotOnInit: boolean;
  snapshotAutoInterval: boolean;
  snapshotBookmarkedOnly: boolean;
  /** Auto-remove disposed signals after X seconds. 0 = immediate, -1 = never */
  autoRemoveDisposedTimer: number;
  /** Auto snapshot interval in seconds. 0 = disabled */
  autoSnapshotIntervalSeconds: number;
  /** Maximum number of history entries per signal */
  signalHistoryLimit: number;
}

export type EventLogEntry = DevToolsEvent & {
  id: number;
  timestamp: number;
  isError?: boolean;
};

// WeakRef type declaration for ES2020 compatibility
declare global {
  class WeakRef<T extends object> {
    constructor(target: T);
    deref(): T | undefined;
  }
}

export interface SnapshotSignal {
  id: string;
  name: string;
  value: unknown;
  signalRef: WeakRef<{ set: (value: unknown) => void }> | null;
}

export interface Snapshot {
  id: string;
  timestamp: number;
  name: string;
  signals: SnapshotSignal[];
}

export interface CompareModalState {
  signalId: string;
  currentValue: unknown;
  historyValue: unknown;
  historyTimestamp: number;
}

